### ISSUE TITLE
 AI and Accessibility Research page

### ISSUE THREAD

**Issue by merylke** [w3c/wai-fundamentals-overview#103]
The [AI and Accessibility Research page](https://www.w3.org/WAI/research/ai2023/) is a great resource! Thank you. Would it be possible to make the paragraphs shorter in all the descriptions? I think you know why I'm suggesting this.

**Comment by shawna-slh** [comment]
@leticiaseixas @iadawn @carlosapaduarte

**Comment by remibetin** [comment]
I am closing this issue that has been resolved by https://github.com/w3c/wai-fundamentals-overview/pull/105!
