### ISSUE TITLE
English: "Accessibility, Usability, and Inclusion"

### ISSUE THREAD

**Issue by vmmiller** [w3c/wai-fundamentals-overview#42]
English: "Accessibility, Usability, and Inclusion"

French translation: Accessibilité, ergonomie, et inclusion (en anglais)

I was just wondering if "usabilité" could be used or is "ergonomie" the usual translation for usability, usability testing etc.

_Originally posted by @vmmiller in https://github.com/w3c/wai-fundamentals-overview/pull/33#discussion_r614884229_

**Comment by slhenry** [comment]
I htink you said to close this?
