### ISSUE TITLE
[es] page for translation:  Accessibility Fundamentals Overview

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-fundamentals-overview#58]
@cmuncharaz Do you want to do this translation, or should I try to find someone else?

**Comment by cmuncharaz** [comment]
I accidentally did it and sent a pull request. Please, take my translation as a backup and use the translation provided by other translator if you already found one.

**Comment by remibetin** [comment]
Resolved by https://github.com/w3c/wai-fundamentals-overview/pull/63
